// task 1
let count = 5;
count = 6;
console.log(count);

//task 2
const user = { user_name: "Pavlo", user_age: 18 };
console.log(user.user_name, user.user_age);

user.user_age = 19;
console.log(user.user_age); // there is no error. It actually printed 19

// task 3
const numbers = [1, 2, 3, 4, 5, 6, 7];
console.log(numbers);
numbers.push(8);
console.log(numbers);

